/**
 * Khai báo trường lõi CỦA ĐIỀU PHỐI cho Sổ đăng ký trường nền tảng (ĐP-3
 * §6.2 mục 3.2). Coordinator tự khai trường của mình ở đây — không khai ở
 * `field-platform/domain` — để field-platform không phải import ngược vào
 * coordinator (tránh vòng phụ thuộc, giữ field-platform là hạ tầng dùng
 * chung cho mọi module sau này).
 *
 * ĐỢT ĐẦU (26/09/2026, ĐP-3): mới khai một lô đại diện các trường lõi ĐÃ
 * XÂY thật trong `order-view.ts`/`http-schemas.ts` — KHÔNG PHẢI toàn bộ 90
 * mục "CÓ" của Đặc tả trường §18. Khai nốt phần còn lại là việc chép dữ
 * liệu (không phải kiến trúc mới), để làm dần khi mỗi giai đoạn ĐP-4 xây
 * thêm trường — mỗi trường mới bắt buộc khai ở đây CÙNG LƯỢT (quy tắc
 * chung #7 của kế hoạch). `scripts/check-field-registry.ts` không đòi phủ
 * 100% Đặc tả trường; nó chỉ đòi những gì đã khai ở đây phải khớp thật với
 * `order-view.ts` và danh mục hành vi thật — nói cách khác, sổ có thể
 * CHƯA ĐẦY ĐỦ nhưng không được phép SAI.
 */
import type { CoreFieldDefinition } from "@/modules/field-platform/domain/core-field-registry"
import { INTERNAL_ONLY_VISIBILITY } from "@/modules/field-platform/domain/core-field-registry"

const ALL_VISIBLE_EXCEPT_CUSTOMER = { INTERNAL: true, PARTNER: true, SHIPPER: true, CUSTOMER: false } as const
const INTERNAL_AND_PARTNER = { INTERNAL: true, PARTNER: true, SHIPPER: false, CUSTOMER: false } as const

export const COORDINATOR_CORE_FIELDS: readonly CoreFieldDefinition[] = [
  // ── Người mua (Sales Order Intake, T01) ───────────────────────────────
  {
    key: "customerName",
    entity: "ORDER",
    dataType: "TEXT",
    label: "Tên người mua",
    requirement: "REQUIRED",
    requiredAtStage: "INTAKE",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.buyer", order: 1 }],
  },
  {
    key: "customerPhone",
    entity: "ORDER",
    dataType: "PHONE",
    label: "SĐT người mua",
    requirement: "REQUIRED",
    requiredAtStage: "INTAKE",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "PII",
    placements: [{ placement: "T01.buyer", order: 2 }],
  },
  {
    key: "customerId",
    entity: "ORDER",
    dataType: "TEXT",
    label: "Khách hàng (từ Customer Master Index)",
    description: "Có thì tên/SĐT/hạng lấy từ CMI, bỏ qua giá trị nhập tay (ĐP-2.9).",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.buyer", order: 0 }],
  },
  // ── Người nhận ─────────────────────────────────────────────────────────
  {
    key: "recipientName",
    entity: "ORDER",
    dataType: "TEXT",
    label: "Tên người nhận",
    requirement: "REQUIRED",
    requiredAtStage: "INTAKE",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.recipient", order: 1 }],
  },
  {
    key: "recipientPhone",
    entity: "ORDER",
    dataType: "PHONE",
    label: "SĐT người nhận",
    requirement: "REQUIRED",
    requiredAtStage: "INTAKE",
    visibility: { INTERNAL: true, PARTNER: false, SHIPPER: true, CUSTOMER: false },
    sensitivity: "PII",
    placements: [{ placement: "T01.recipient", order: 2 }],
  },
  // ── Sản phẩm ───────────────────────────────────────────────────────────
  {
    key: "productId",
    entity: "ORDER",
    dataType: "TEXT",
    label: "Sản phẩm (Product Master Index)",
    description: "Tuỳ chọn — vẫn tạo được đơn mẫu ngoài danh mục (ĐP-2.6).",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.product", order: 1 }],
  },
  {
    key: "productTitle",
    entity: "ORDER",
    dataType: "TEXT",
    label: "Tên sản phẩm hiển thị trên đơn",
    requirement: "REQUIRED",
    requiredAtStage: "INTAKE",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.product", order: 2 }],
  },
  {
    key: "sampleAssetId",
    entity: "ORDER",
    dataType: "ASSET_REF",
    label: "Ảnh mẫu",
    requirement: "RECOMMENDED",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.product", order: 3 }],
  },
  // ── Địa chỉ giao ───────────────────────────────────────────────────────
  {
    key: "deliveryAddress",
    entity: "ORDER",
    dataType: "STRUCTURED_ADDRESS",
    label: "Địa chỉ giao (4 tầng)",
    requirement: "REQUIRED",
    requiredAtStage: "INTAKE",
    visibility: { INTERNAL: true, PARTNER: false, SHIPPER: true, CUSTOMER: false },
    sensitivity: "PII",
    placements: [{ placement: "T01.delivery", order: 1 }],
  },
  {
    key: "deliveryTargetAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Thời điểm giao mong muốn",
    requirement: "RECOMMENDED",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.delivery", order: 2 }],
  },
  // ── Thiệp ──────────────────────────────────────────────────────────────
  {
    key: "cardRequired",
    entity: "ORDER",
    dataType: "BOOLEAN",
    label: "Đơn có thiệp/băng rôn",
    requirement: "OPTIONAL",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.card", order: 1 }],
  },
  {
    key: "cardMessage",
    entity: "ORDER",
    dataType: "LONG_TEXT",
    label: "Lời thiệp",
    description: "Bắt buộc khi cardRequired = true — luật điều kiện nằm ở http-schemas.ts, chưa chuyển vào cổng bắt buộc-theo-bước (3.10) ở đợt này.",
    requirement: "RECOMMENDED",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.card", order: 2 }],
  },
  // ── Ghi chú — hai kênh tách biệt (ĐP-1.7) ────────────────────────────────
  {
    key: "internalNote",
    entity: "ORDER",
    dataType: "LONG_TEXT",
    label: "Ghi chú nội bộ",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.note", order: 1 }],
  },
  {
    key: "partnerInstruction",
    entity: "ORDER",
    dataType: "LONG_TEXT",
    label: "Ghi chú phân công cho đối tác",
    requirement: "OPTIONAL",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T06.assign", order: 1 }],
  },
  // ── Tiền — mức sàn: giá bán/trả đối tác không hiện ra ngoài INTERNAL/PARTNER phù hợp ──
  {
    key: "unitPriceVnd",
    entity: "ORDER",
    dataType: "MONEY_VND",
    label: "Giá bán cho khách",
    description: "Mức sàn: KHÔNG hiện với PARTNER/SHIPPER/CUSTOMER (ĐP-1.1 — gỡ khỏi PNG T07).",
    requirement: "REQUIRED",
    requiredAtStage: "INTAKE",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    floorInternalOnly: true,
    placements: [{ placement: "T01.pricing", order: 1 }],
  },
  {
    key: "partnerPayoutVnd",
    entity: "ORDER",
    dataType: "MONEY_VND",
    label: "Số tiền trả đối tác",
    requirement: "OPTIONAL",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T06.assign", order: 2 }],
  },
  // ── ĐP-4a.1/4a.5/4a.9 (26–27/09/2026) — Phân loại, bàn giao, lập kế hoạch ──
  // Mức REQUIRED sàn ở đây CỐ Ý để OPTIONAL (không `requiredAtStage`) dù đặc
  // tả gốc liệt các trường này ở P0 (§3.1) — nâng lên REQUIRED ngay ở lớp mã
  // sẽ chặn RỜI INTAKE của MỌI đơn hiện có (kể cả bộ test cũ chưa từng gửi
  // các trường này), lặp lại đúng kiểu hồi quy đã gặp với `priority` (xem
  // TRANG_THAI.md 27/09/2026). Muốn bắt buộc thật cho một tổ chức cụ thể:
  // dùng `field_config_overrides` (Console Vận hành) để NÂNG mức — không sửa
  // sàn ở đây.
  {
    key: "channel",
    entity: "ORDER",
    dataType: "SELECT",
    label: "Kênh tiếp nhận",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    catalogKey: "channel",
    placements: [{ placement: "T01.classify", order: 1 }],
  },
  {
    key: "orderType",
    entity: "ORDER",
    dataType: "SELECT",
    label: "Loại đơn",
    description: "Kích hoạt nhóm trường có điều kiện (§12) và mức ưu tiên gợi ý.",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    catalogKey: "orderType",
    placements: [{ placement: "T01.classify", order: 2 }],
  },
  {
    key: "serviceLevel",
    entity: "ORDER",
    dataType: "SELECT",
    label: "Cam kết thời gian giao",
    description: "Dùng tính deliveryTargetAt theo hành vi (ĐP-4a.2).",
    requirement: "OPTIONAL",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    catalogKey: "serviceLevel",
    placements: [{ placement: "T01.classify", order: 3 }],
  },
  {
    key: "deliveryType",
    entity: "ORDER",
    dataType: "SELECT",
    label: "Hình thức giao",
    requirement: "OPTIONAL",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    catalogKey: "deliveryType",
    placements: [{ placement: "T01.classify", order: 4 }],
  },
  {
    key: "deliveryLocationType",
    entity: "ORDER",
    dataType: "SELECT",
    label: "Loại địa điểm giao",
    description: "Kích hoạt nhóm trường có điều kiện (§12: khách sạn/bệnh viện/toà nhà).",
    requirement: "OPTIONAL",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    catalogKey: "deliveryLocationType",
    placements: [{ placement: "T01.classify", order: 5 }],
  },
  {
    key: "priority",
    entity: "ORDER",
    dataType: "SELECT",
    label: "Mức ưu tiên",
    description: "Máy GỢI Ý theo §2.15.1 khi để trống — người quyết định cuối.",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    catalogKey: "priority",
    placements: [{ placement: "T01.classify", order: 6 }, { placement: "T05.card", order: 1 }],
  },
  {
    key: "receivedAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Thời điểm đơn thực sự đến",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.classify", order: 7 }],
  },
  {
    key: "deliveryWindowStart",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Đầu khung giờ giao",
    description: "Dùng khi serviceLevel = TIME_SLOT (§2.15.2).",
    requirement: "OPTIONAL",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.delivery", order: 10 }],
  },
  {
    key: "deliveryWindowEnd",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Cuối khung giờ giao",
    requirement: "OPTIONAL",
    visibility: ALL_VISIBLE_EXCEPT_CUSTOMER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T01.delivery", order: 11 }],
  },
  // ── ĐP-4a.5 (27/09/2026) — T02 Sales Order Brief, bàn giao Sales → Điều phối ──
  {
    key: "specialRequirements",
    entity: "ORDER",
    dataType: "LONG_TEXT",
    label: "Yêu cầu đặc biệt của khách",
    requirement: "OPTIONAL",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T02.brief", order: 1 }],
  },
  {
    key: "handoffAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Mốc bàn giao cho Điều phối",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T02.brief", order: 2 }],
  },
  // ── ĐP-4a.9 (27/09/2026) — Form Lập kế hoạch đơn (Đặc tả trường §4.2) ────
  {
    key: "plannedAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Mốc lập kế hoạch xong",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "Form.planning", order: 1 }],
  },
  {
    key: "productionDeadlineAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Hạn sản xuất xong",
    requirement: "OPTIONAL",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "Form.planning", order: 2 }],
  },
  {
    key: "pickupTargetAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Hạn lấy hàng đi giao",
    requirement: "OPTIONAL",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "Form.planning", order: 3 }],
  },
  {
    key: "technicalInstruction",
    entity: "ORDER",
    dataType: "LONG_TEXT",
    label: "Hướng dẫn kỹ thuật cho thợ cắm",
    requirement: "OPTIONAL",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "Form.planning", order: 4 }],
  },
  {
    key: "nextActionOwnerId",
    entity: "ORDER",
    dataType: "TEXT",
    label: "Người phụ trách hành động kế tiếp",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "Form.planning", order: 5 }],
  },
  {
    key: "partnerSelectionDeadlineAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Hạn chọn đối tác",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "Form.planning", order: 6 }],
  },
  // ── ĐP-4a.3 bù + 4a.8 (27/09/2026) — Cách thu, hạn thu phần còn lại ──────
  {
    key: "collectionMethod",
    entity: "ORDER",
    dataType: "SELECT",
    label: "Cách thu phần còn lại",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    catalogKey: "collectionMethod",
    placements: [{ placement: "T05.card", order: 2 }],
  },
  {
    key: "collectionDueAt",
    entity: "ORDER",
    dataType: "DATETIME",
    label: "Hạn thu phần còn lại",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T05.card", order: 3 }],
  },
  // ── Đối tác (PARTNER entity) ─────────────────────────────────────────────
  {
    key: "partnerName",
    entity: "PARTNER",
    dataType: "TEXT",
    label: "Tên đối tác",
    requirement: "REQUIRED",
    visibility: INTERNAL_AND_PARTNER,
    sensitivity: "NORMAL",
    placements: [{ placement: "T06.candidate", order: 1 }],
  },
  {
    key: "partnerPhone",
    entity: "PARTNER",
    dataType: "PHONE",
    label: "SĐT đối tác",
    requirement: "REQUIRED",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "PII",
    placements: [{ placement: "T06.candidate", order: 2 }],
  },
  {
    key: "partnerAddress",
    entity: "PARTNER",
    dataType: "TEXT",
    label: "Địa chỉ đối tác",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T06.candidate", order: 3 }],
  },
  {
    key: "partnerCapacityDaily",
    entity: "PARTNER",
    dataType: "NUMBER",
    label: "Công suất mỗi ngày",
    requirement: "OPTIONAL",
    visibility: INTERNAL_ONLY_VISIBILITY,
    sensitivity: "NORMAL",
    placements: [{ placement: "T06.candidate", order: 4 }],
  },
] as const
