/**
 * Danh mục Journey tĩnh cho 3 Role cấp cao.
 * Nguồn đặc tả: FLORAOS_CORE_JOURNEY_FIRST_UX_ARCHITECTURE_FINAL.md (§5.3, §7, §11)
 *
 * Luật Clean Architecture: Không import React, không import Prisma.
 * UX Lint R8: Không hiển thị mã kỹ thuật (M01a, M04b, RBAC...) trên label/description.
 */

import type { JourneyDefinition } from "./journey-model"

/**
 * Danh mục hành trình cho Quản trị Cửa hàng (Store Admin)
 */
export const STORE_JOURNEYS: JourneyDefinition[] = [
  {
    id: "greeting-card-hub",
    goal: "Thẻ Chào mẫu hoa",
    description: "Tạo bộ sưu tập hoa, gửi link cho khách lướt chọn mẫu, theo dõi thanh toán và điều phối cắm hoa giao đến tay người nhận",
    icon: "Sparkles",
    badgeText: "Tính năng trọng tâm",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/the-chao",
    steps: [
      {
        id: "manage-greeting-catalog",
        label: "Quản lý Bộ Sưu Tập & Đơn hàng",
        inputType: "NONE" as const,
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "view-store-overview",
    goal: "Xem báo cáo",
    description: "Nắm bắt doanh thu, đơn hàng, mức độ sử dụng FloraOS và kho tư liệu đã tạo",
    icon: "BarChart3",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/so-lieu",
    steps: [
      {
        id: "view-growth-dashboard",
        label: "Bảng tổng quan tăng trưởng",
        inputType: "NONE",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "market-intelligence-explore",
    goal: "Xem mẫu hoa đang được yêu thích",
    description: "Biết khách đang chuộng kiểu hoa, màu sắc và mức giá nào để tiệm cắm bán theo",
    icon: "TrendingUp",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/market-intelligence",
    steps: [
      {
        id: "view-trends",
        label: "Khám phá bảng vàng xu hướng",
        inputType: "NONE",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "analyze-product-photo",
    goal: "Tạo Thẻ sản phẩm từ ảnh",
    description: "Chụp ảnh hoa tại tiệm để tự động phân tích loại hoa, ước tính chi phí và tạo mẫu bán",
    icon: "Camera",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/san-pham",
    steps: [
      {
        id: "upload-product-photo",
        label: "Tải ảnh sản phẩm",
        description: "Chọn ảnh bó hoa, giỏ hoa hoặc kệ hoa cần phân tích",
        inputType: "IMAGE_UPLOAD",
        isOptional: false,
        nextStepId: "review-analysis",
      },
      {
        id: "review-analysis",
        label: "Xem kết quả phân tích & lưu",
        description: "Kiểm tra danh mục thành phần hoa và thông số định giá",
        inputType: "CONFIRMATION",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "create-product-quote",
    goal: "Tạo Thẻ báo giá sản phẩm",
    description: "Tạo bộ báo giá hoa theo nhu cầu khách mua hoa hoặc thẻ báo giá cho đối tác shop",
    icon: "Receipt",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/bao-gia",
    steps: [
      {
        id: "select-product-for-quote",
        label: "Chọn hoặc nhập sản phẩm",
        inputType: "PRODUCT_SELECT",
        isOptional: false,
        nextStepId: "generate-quote",
      },
      {
        id: "generate-quote",
        label: "Hoàn thiện và gửi báo giá",
        inputType: "CONFIRMATION",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "create-marketing-copy",
    goal: "Viết nội dung bài đăng cho các nền tảng",
    description: "Gợi ý lời chúc, câu chuyện và bài đăng thu hút khách trên các mạng xã hội",
    icon: "FileText",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/creative-studio",
    steps: [
      {
        id: "choose-content-angle",
        label: "Chọn góc tiếp cận và cảm xúc",
        inputType: "CONFIG_SELECT",
        isOptional: false,
        nextStepId: "generate-copy",
      },
      {
        id: "generate-copy",
        label: "Hoàn chỉnh nội dung bài viết",
        inputType: "CONFIRMATION",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "create-audio-voiceover",
    goal: "Tạo giọng đọc cho bài đăng",
    description: "Tạo giọng đọc truyền cảm và nhạc nền du dương cho các bài đăng giới thiệu hoa",
    icon: "Volume2",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/creative-studio",
    steps: [
      {
        id: "select-audio-script",
        label: "Chọn kịch bản thuyết minh",
        inputType: "CONFIG_SELECT",
        isOptional: false,
        nextStepId: "render-audio-voice",
      },
      {
        id: "render-audio-voice",
        label: "Xuất file âm thanh & nhạc nền",
        inputType: "CONFIRMATION",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "create-marketing-image",
    goal: "Tạo ảnh quảng cáo từ ảnh gốc",
    description: "Biến ảnh hoa chụp tại tiệm thành ảnh quảng cáo đẹp trên nhiều bối cảnh khác nhau",
    icon: "Image",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/creative-studio",
    steps: [
      {
        id: "choose-product-photo",
        label: "Chọn ảnh mẫu sản phẩm",
        inputType: "IMAGE_UPLOAD",
        isOptional: false,
        nextStepId: "render-background",
      },
      {
        id: "render-background",
        label: "Chọn bối cảnh và kết xuất",
        inputType: "CONFIG_SELECT",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "create-product-video",
    goal: "Tạo video chuyển động từ ảnh hoa",
    description: "Tạo video ngắn có chuyển động lia góc từ một ảnh hoa để đăng lên mạng xã hội",
    icon: "Video",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/creative-studio",
    steps: [
      {
        id: "select-video-storyboard",
        label: "Chọn mạch câu chuyện video",
        inputType: "CONFIG_SELECT",
        isOptional: false,
        nextStepId: "render-video",
      },
      {
        id: "render-video",
        label: "Kết xuất video độ nét cao",
        inputType: "CONFIRMATION",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "create-catalog-collection",
    goal: "Tạo trang giới thiệu và bán hoa",
    description: "Tạo trang web giới thiệu tiệm hoa và bộ sưu tập các mẫu hoa theo từng dịp lễ",
    icon: "BookOpen",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/catalog",
    steps: [
      {
        id: "curate-products",
        label: "Tuyển chọn danh sách hoa",
        inputType: "PRODUCT_SELECT",
        isOptional: false,
        nextStepId: "publish-catalog",
      },
      {
        id: "publish-catalog",
        label: "Phát hành link xem trực tuyến",
        inputType: "CONFIRMATION",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "create-order",
    goal: "Tiếp nhận & Xử lý đơn hàng (Dành cho Điện Hoa)",
    description: "Nhập thông tin người nhận, mẫu hoa, thời gian giao và in phiếu giao việc cho thợ cắm",
    icon: "ShoppingCart",
    badgeText: "Điện Hoa",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/don-hang",
    steps: [
      {
        id: "input-order-details",
        label: "Nhập thông tin đơn hàng",
        inputType: "ORDER_INPUT",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "manage-customers",
    goal: "Quản lý khách hàng",
    description: "Quản lý hồ sơ khách, lịch sử mua hoa, sở thích và nhắc ngày kỷ niệm để chăm sóc",
    icon: "Users",
    roleScope: "STORE",
    category: "SINGLE",
    primaryHref: "/khach-hang",
    steps: [
      {
        id: "browse-customer-profiles",
        label: "Danh sách hồ sơ khách hàng",
        inputType: "NONE",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "launch-product-combo",
    goal: "Tạo bộ nội dung bán hoa tự động",
    description: "Quy trình trọn gói từ một ảnh hoa gốc: định giá, tạo ảnh đẹp, viết bài và chuẩn bị video",
    icon: "Rocket",
    badgeText: "Gói quy trình",
    roleScope: "STORE",
    category: "COMBO",
    steps: [
      {
        id: "combo-step-photo",
        label: "Ảnh mẫu ban đầu",
        inputType: "IMAGE_UPLOAD",
        isOptional: false,
        nextStepId: "combo-step-quote",
      },
      {
        id: "combo-step-quote",
        label: "Định giá & báo giá",
        inputType: "NONE",
        isOptional: false,
        nextStepId: "combo-step-image",
      },
      {
        id: "combo-step-image",
        label: "Hình ảnh studio",
        inputType: "NONE",
        isOptional: false,
        nextStepId: "combo-step-content",
      },
      {
        id: "combo-step-content",
        label: "Nội dung tiếp thị",
        inputType: "NONE",
        isOptional: true,
        nextStepId: "combo-step-video",
      },
      {
        id: "combo-step-video",
        label: "Video giới thiệu",
        inputType: "NONE",
        isOptional: true,
        nextStepId: "combo-step-publish",
      },
      {
        id: "combo-step-publish",
        label: "Mở bán đa kênh",
        inputType: "CONFIRMATION",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
  {
    id: "customer-service-chatbot",
    goal: "Tư vấn và nhận đơn tự động",
    description: "Trợ lý AI tư vấn mẫu hoa, báo giá và tiếp nhận thông tin đặt hoa của khách 24/7",
    icon: "Bot",
    badgeText: "Khách 24/7",
    roleScope: "STORE",
    category: "AI_SUGGEST",
    primaryHref: "/hoi-thoai",
    steps: [
      {
        id: "chatbot-channel-settings",
        label: "Kênh tư vấn & nhận đơn",
        inputType: "CONFIG_SELECT",
        isOptional: false,
        nextStepId: null,
      },
    ],
  },
]

/**
 * Danh mục hành trình cho Quản trị Nền tảng (Platform Admin)
 */
export const PLATFORM_JOURNEYS: JourneyDefinition[] = [
  {
    id: "view-platform-overview",
    goal: "Xem báo cáo hệ thống",
    description: "Tình hình sử dụng, doanh thu bản quyền, số lượng tổ chức đang hoạt động",
    icon: "BarChart3",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh",
    steps: [{ id: "step-1", label: "Tổng quan vận hành", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "manage-organizations",
    goal: "Quản lý tổ chức",
    description: "Thiết lập cửa hàng đơn lẻ, chuỗi chi nhánh và mạng lưới điện hoa",
    icon: "Building2",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/to-chuc",
    steps: [{ id: "step-1", label: "Danh sách tổ chức", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "manage-users",
    goal: "Quản lý người dùng",
    description: "Cấp tài khoản, phân vai vận hành và kiểm soát quyền truy cập",
    icon: "UserCog",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/nguoi-dung",
    steps: [{ id: "step-1", label: "Danh sách người dùng", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "manage-subscriptions",
    goal: "Quản lý gói dịch vụ",
    description: "Cấu hình gói tháng, gói năm, chính sách giá và gia hạn",
    icon: "CreditCard",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/goi-dich-vu",
    steps: [{ id: "step-1", label: "Gói dịch vụ", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "manage-capabilities",
    goal: "Quản lý tính năng",
    description: "Kiểm soát danh mục năng lực và trần cứng hệ thống",
    icon: "Puzzle",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/nang-luc",
    steps: [{ id: "step-1", label: "Ma trận tính năng", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "manage-ai-credit",
    goal: "Trí tuệ nhân tạo & Định mức",
    description: "Cấu hình mô hình thông minh, giám sát lượt gọi và định mức tài nguyên",
    icon: "Bot",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/muc-dung",
    steps: [{ id: "step-1", label: "Quản lý mô hình", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "manage-integrations",
    goal: "Quản lý kết nối nền tảng",
    description: "Kết nối cổng thanh toán, mạng xã hội, kênh nhắn tin và giao vận",
    icon: "Plug",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/ket-noi",
    steps: [{ id: "step-1", label: "Cổng kết nối", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "system-health",
    goal: "Sức khỏe hệ thống",
    description: "Giám sát máy chủ, cơ sở dữ liệu, hàng đợi tác vụ và độ trễ",
    icon: "Activity",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/suc-khoe",
    steps: [{ id: "step-1", label: "Tình trạng máy chủ", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "system-settings",
    goal: "Cài đặt hệ thống",
    description: "Tham số toàn cục, mẫu thông báo và cấu hình mặc định",
    icon: "Settings",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/truong-du-lieu",
    steps: [{ id: "step-1", label: "Tham số toàn cục", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "security-audit",
    goal: "Quản trị & Kiểm toán",
    description: "Nhật ký truy cập, phát hiện rủi ro bảo mật và phân quyền",
    icon: "ShieldAlert",
    roleScope: "PLATFORM",
    category: "SINGLE",
    primaryHref: "/van-hanh/nhat-ky",
    steps: [{ id: "step-1", label: "Nhật ký kiểm toán", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
]

/**
 * Danh mục hành trình cho Quản trị Mạng lưới Điện hoa (Flower Network Admin)
 */
export const NETWORK_JOURNEYS: JourneyDefinition[] = [
  {
    id: "network-overview",
    goal: "Báo cáo toàn hệ thống điện hoa",
    description: "Theo dõi dòng đơn điều phối, tỷ lệ nhận đơn và doanh số toàn mạng lưới",
    icon: "Network",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    steps: [{ id: "step-1", label: "Trung tâm điều hành", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "network-products",
    goal: "Quản lý sản phẩm mạng lưới",
    description: "Chuẩn hóa danh mục mẫu hoa chung cho các tiệm thành viên nhận làm",
    icon: "Flower2",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    primaryHref: "/san-pham",
    steps: [{ id: "step-1", label: "Sản phẩm mạng lưới", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "network-sales",
    goal: "Bán hàng & Đơn đặt",
    description: "Tiếp nhận đơn hàng điện hoa liên tỉnh và phân bổ nhanh chóng",
    icon: "ShoppingBag",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    primaryHref: "/don-hang",
    steps: [{ id: "step-1", label: "Quản lý đơn hàng", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "network-dispatch",
    goal: "Điều phối đơn hàng",
    description: "Chuyển đơn thông minh tới cửa hàng hoa đối tác gần điểm giao nhất",
    icon: "Truck",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    primaryHref: "/dieu-phoi",
    steps: [{ id: "step-1", label: "Bảng điều phối trung tâm", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "network-partners",
    goal: "Quản lý đối tác tiệm hoa",
    description: "Đánh giá chất lượng cắm hoa, tỷ lệ hoàn thành đúng hẹn của đối tác",
    icon: "Handshake",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    primaryHref: "/doi-tac",
    steps: [{ id: "step-1", label: "Mạng lưới đối tác", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "network-crm",
    goal: "Khách hàng & Chăm sóc đối tác",
    description: "Hỗ trợ khách hàng VIP và giải quyết khiếu nại chất lượng sản phẩm",
    icon: "Users2",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    primaryHref: "/khach-hang",
    steps: [{ id: "step-1", label: "Chăm sóc khách hàng", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "network-marketing",
    goal: "Chiến dịch tiếp thị liên kết",
    description: "Quảng bá thương hiệu mạng lưới và thúc đẩy lưu lượng đặt hoa toàn quốc",
    icon: "Megaphone",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    primaryHref: "/marketing",
    steps: [{ id: "step-1", label: "Chiến dịch tiếp thị", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
  {
    id: "network-finance",
    goal: "Đối soát tài chính & Hoa hồng",
    description: "Tính toán tiền cắm hoa, hoa hồng giới thiệu và thanh toán cho đối tác",
    icon: "Coins",
    roleScope: "FLOWER_NETWORK",
    category: "SINGLE",
    primaryHref: "/tai-chinh",
    steps: [{ id: "step-1", label: "Đối soát hoa hồng", inputType: "NONE", isOptional: false, nextStepId: null }],
  },
]
