/**
 * Catalog definitions for Greeting Card Templates (Mẫu Thẻ Chào).
 * Pure TypeScript — No Prisma or external infrastructure imports.
 */

import type { GreetingTemplateId, GreetingCardTemplateDef } from "./greeting-template-types"

export const GREETING_TEMPLATES: Record<GreetingTemplateId, GreetingCardTemplateDef> = {
  // 01
  "editorial-luxury": {
    id: "editorial-luxury",
    styleNumber: "01",
    name: "Editorial Luxury",
    subtitle: "Sang trọng, tạp chí thời trang",
    badge: "Editorial",
    category: "swipe-style",
    isDefault: true,
    description: "Nền kem trầm ấm, font Serif tương phản cao, typography to bản sau bó hoa, viền mảnh tinh tế và khoảng thở rộng rãi chuẩn tạp chí.",
    tag: "Sang trọng & Thời trang",
    features: [
      "Typography Serif khổ lớn sang trọng partially overlap sau sản phẩm",
      "Nền tối sang trọng kết hợp viền mảnh hairline tinh xảo",
      "Bộ nút điều hướng tròn tối giản hỗ trợ vuốt trái/phải mượt mà",
      "Nút chốt mẫu chuẩn xác giữ tỷ lệ chuyển đổi cao",
    ],
    recommendedFor: "Bó hoa cao cấp, hoa tình yêu kỷ niệm, khách hàng yêu phong cách tinh tế",
  },
  // 02
  "minimal-clean": {
    id: "minimal-clean",
    styleNumber: "02",
    name: "Minimal Clean",
    subtitle: "Tối giản, hiện đại",
    badge: "Minimal",
    category: "swipe-style",
    description: "Nền trắng ngà thanh thoát, font Sans-serif hiện đại, tối đa khoảng trống quang đãng tôn trọn vẹn vẻ đẹp tự nhiên của đóa hoa.",
    tag: "Tối giản & Tinh khôi",
    features: [
      "Khoảng trắng tối đa (Negative Space) bao quanh bó hoa",
      "Không viền thẻ, không hiệu ứng rườm rà, tập trung 100% vào hoa",
      "Bóng tiếp xúc mềm mại tự nhiên",
      "Nút chốt mẫu 1-chạm dứt khoát",
    ],
    recommendedFor: "Hoa tulip, hoa cúc họa mi, phong cách tươi sáng",
  },
  // 03
  "cinematic-dark": {
    id: "cinematic-dark",
    styleNumber: "03",
    name: "Cinematic Dark",
    subtitle: "Điện ảnh, ấn tượng",
    badge: "Cinematic",
    category: "swipe-style",
    description: "Nền đen studio điện ảnh, ánh sáng spotlight gom tiêu điểm, chữ nghiêng nghệ thuật và điểm nhấn màu hổ phách ấm áp.",
    tag: "Huyền bí & Ấn tượng",
    features: [
      "Nền đen studio kết hợp ánh sáng viền (Rim Light) nổi bật",
      "Tiêu đề uốn lượn phong cách chữ ký sang trọng",
      "Độ tương phản cao tôn sắc hoa rực rỡ",
      "Nút thả tim màu hổ phách nổi bật",
    ],
    recommendedFor: "Bó hoa hồng đỏ nhập khẩu, phong cách quý phái huyền bí",
  },
  // 04
  "romantic-pastel": {
    id: "romantic-pastel",
    styleNumber: "04",
    name: "Romantic Pastel",
    subtitle: "Lãng mạn, mềm mại",
    badge: "Pastel",
    category: "swipe-style",
    description: "Dải màu hồng pastel, đào và tím oải hương dịu nhẹ, hiệu ứng cánh hoa rơi mơ màng và phông chữ uốn lượn ngọt ngào.",
    tag: "Ngọt ngào & Lãng mạn",
    features: [
      "Dải chuyển màu pastel dịu mắt chống chói lóa",
      "Họa tiết hạt ánh sáng và cánh hoa bay mềm mại",
      "Nhãn tiêu đề uốn lượn Blooming Moments ngọt ngào",
      "Nút hành động tông hồng phấn nữ tính",
    ],
    recommendedFor: "Hoa mẫu đơn, hoa sinh nhật bạn gái, ngày lễ tình nhân 20/10 & 8/3",
  },
  // 05
  "botanical-frame": {
    id: "botanical-frame",
    styleNumber: "05",
    name: "Botanical Frame",
    subtitle: "Thiên nhiên, tinh tế",
    badge: "Botanical",
    category: "swipe-style",
    description: "Khung viền lá cây thực vật vẽ nét mảnh ở các góc, nền giấy thô ấm áp, mang trọn hơi thở thiên nhiên thuần khiết.",
    tag: "Thiên nhiên & Tinh tế",
    features: [
      "Họa tiết cành lá botanical thanh lịch ở các góc khung hình",
      "Nền giấy ngà ấm áp mộc mạc",
      "Tỷ lệ trang trí <10% không lấn át sản phẩm chính",
      "Nút bấm tông màu đất và ô-liu tự nhiên",
    ],
    recommendedFor: "Bó hoa cẩm tú cầu, hoa lan, phong cách mộc mạc Vintage",
  },
  // 06
  "glassmorphism": {
    id: "glassmorphism",
    styleNumber: "06",
    name: "Glassmorphism",
    subtitle: "Hiện đại, trong suốt",
    badge: "Glass",
    category: "swipe-style",
    description: "Tấm thông tin kính mờ (Frosted Glass Panel) nổi trên nền ảnh, viền sáng khúc xạ sang trọng chuẩn công nghệ hiện đại.",
    tag: "Trong suốt & Hiện đại",
    features: [
      "Tấm kính mờ backdrop-blur nổi bật trên nền ảnh",
      "Viền phản chiếu ánh sáng trắng tinh tế",
      "Độ che phủ <35% giữ trọn bố cục hoa phía sau",
      "Nút điều khiển kính mờ đồng bộ",
    ],
    recommendedFor: "Hoa hướng dương, hoa hiện đại, khách hàng trẻ yêu công nghệ",
  },
  // 07
  "real-life-shop": {
    id: "real-life-shop",
    styleNumber: "07",
    name: "Real Life - Shop Photo",
    subtitle: "Ảnh chụp thực tế, tự nhiên",
    badge: "Shop Photo",
    category: "swipe-style",
    description: "Bối cảnh cửa hàng hoa thực tế, góc chụp trước thềm tiệm chân thực, ánh sáng ấm cúng tạo cảm giác gần gũi tin cậy.",
    tag: "Chân thực & Đời sống",
    features: [
      "Bối cảnh tiệm hoa thực tế với ánh đèn ấm áp",
      "Bóng tiếp xúc tự nhiên đổ dưới sản phẩm",
      "Nơ ruy-băng đỏ thực tế tạo điểm nhấn thân quen",
      "Thông số gọn gàng tôn trọng ảnh thật",
    ],
    recommendedFor: "Bó hoa đỏ truyền thống, khách thích ảnh chụp thật tại tiệm",
  },
  // 08
  "real-life-daylight": {
    id: "real-life-daylight",
    styleNumber: "08",
    name: "Real Life - Daylight",
    subtitle: "Ánh sáng tự nhiên, đời thực",
    badge: "Daylight",
    category: "swipe-style",
    description: "Ánh sáng mặt trời ban ngày rực rỡ, phông nền ngoài trời hoặc cạnh cửa sổ tự nhiên, chuẩn góc chụp smartphone cao cấp.",
    tag: "Nắng sớm & Tươi mới",
    features: [
      "Mô phỏng ánh sáng tự nhiên cạnh cửa sổ rực rỡ",
      "Màu sắc cánh hoa tươi tắn trung thực",
      "Phông chữ đơn giản không che khuất nắng sớm",
      "Gợi cảm giác hoa vừa cắt từ vườn",
    ],
    recommendedFor: "Hoa tulip, hoa hồng pastel, tặng buổi sáng tươi vui",
  },
  // 09
  "real-life-in-store": {
    id: "real-life-in-store",
    styleNumber: "09",
    name: "Real Life - In Store",
    subtitle: "Trong cửa hàng, gần gũi",
    badge: "In Store",
    category: "swipe-style",
    description: "Không gian bên trong xưởng hoa với kệ gỗ, ánh đèn vàng ấm áp và khung cảnh làm việc đầy chất nghệ nhân.",
    tag: "Ấm cúng & Nghệ nhân",
    features: [
      "Kệ hoa gỗ và đèn trang trí phía sau mờ nhẹ (Bokeh)",
      "Độ sâu trường ảnh tạo cảm giác không gian thực",
      "Chất màu ấm cúng mang lại sự an tâm",
      "Nút thao tác mượt mà dễ bấm bằng 1 tay",
    ],
    recommendedFor: "Hoa cúc mẫu đơn, hoa tặng mẹ, hoa gia đình ấm cúng",
  },
  // 10
  "real-life-handheld": {
    id: "real-life-handheld",
    styleNumber: "10",
    name: "Real Life - Handheld",
    subtitle: "Cầm tay, góc chụp casual",
    badge: "Handheld",
    category: "swipe-style",
    description: "Góc chụp ngôi thứ nhất (POV) bàn tay cầm bó hoa bước đi dạo phố, góc máy tự nhiên chuẩn phong cách mạng xã hội.",
    tag: "Casual & POV",
    features: [
      "Góc nhìn cận cảnh cầm tay chân thật",
      "Nhãn tag giấy gói hoa mộc mạc",
      "Góc máy casual tự nhiên như bạn bè gửi cho nhau",
      "Trải nghiệm lướt nhanh tối ưu cho màn hình dọc",
    ],
    recommendedFor: "Bó hoa nhỏ xinh xách tay, sinh viên, khách trẻ năng động",
  },
  // 11
  "lifestyle-context": {
    id: "lifestyle-context",
    styleNumber: "11",
    name: "Lifestyle Context",
    subtitle: "Trong bối cảnh sử dụng",
    badge: "Lifestyle",
    category: "swipe-style",
    description: "Đặt bình hoa trong không gian sống thực tế: bàn trà sáng sớm, tách cafe, cuốn sách mở và vạt nắng dịu êm.",
    tag: "Không gian sống & Thơ mộng",
    features: [
      "Bối cảnh bàn cafe và ánh sáng ban mai nhẹ nhàng",
      "Giúp khách hàng dễ hình dung hoa đặt trong nhà",
      "Bầu không khí thư thái tĩnh lặng",
      "Nút chốt mẫu trang nhã",
    ],
    recommendedFor: "Bình hoa bàn khách, hoa kỷ niệm ngày cưới, trang trí nhà",
  },
  // 12
  "mixed-media": {
    id: "mixed-media",
    styleNumber: "12",
    name: "Mixed Media Style",
    subtitle: "Kết hợp thật và thiết kế",
    badge: "Mixed Media",
    category: "swipe-style",
    description: "Ảnh chụp thật phối cùng nét vẽ tay doodle ngộ nghĩnh, tấm thiệp Polaroid dán băng dính 'Good day ♡' và chữ viết tay đáng yêu.",
    tag: "Sáng tạo & Đáng yêu",
    features: [
      "Nét vẽ tay doodle trái tim lấp lánh nghệ thuật",
      "Tấm thiệp Polaroid dán băng dính Good day xinh xắn",
      "Bố cục layer phối ghép đa chất liệu sinh động",
      "Cảm giác độc bản và thủ công riêng biệt",
    ],
    recommendedFor: "Quà tặng sinh nhật bạn gái, Gen Z, hoa chúc mừng dễ thương",
  },

  // Legacy & Auxiliary Exploratory Decks
  "enterprise-luxury": {
    id: "enterprise-luxury",
    name: "Enterprise Luxury Deck",
    subtitle: "Giao diện Doanh Nghiệp Sang Trọng",
    badge: "Enterprise",
    category: "swipe-style",
    description: "Bộ thẻ 3 lớp không gian (3-Layer Spatial Deck), kính mờ Floating Frosted Glass, danh sách thả tim (Shortlist), bóc tách thành phần hoa (BOM).",
    tag: "Khuyên dùng cho tiệm hoa cao cấp",
    features: [
      "Xếp chồng 3 lớp không gian với hiệu ứng nảy lò xo",
      "Tấm thông tin kính mờ nổi (Floating Frosted Glass)",
      "Chạm đúp (Double-tap) thả tim & khay so sánh mẫu ưng ý",
      "Nút hành động chốt mẫu chuẩn xác, giữ nguyên kênh chuyển đổi",
    ],
    recommendedFor: "Phù hợp nhất cho khách VIP, bó hoa thiết kế, giỏ hoa sự kiện",
  },
  "swipe-classic": {
    id: "swipe-classic",
    name: "Classic Swipe Brochure",
    subtitle: "Lướt Thẻ Cổ Điển Tinh Gọn",
    badge: "Classic",
    category: "swipe-style",
    description: "Trải nghiệm vuốt thẻ tối giản, thanh tiến trình dạng Story quen thuộc.",
    tag: "Tối giản & Tốc độ",
    features: ["Vuốt thẻ cơ bản trái / phải mượt mà", "Nút chốt mẫu trực tiếp 1-chạm"],
    recommendedFor: "Phù hợp cho khách hàng thích sự quen thuộc, đơn giản",
  },
  "lookbook-grid": {
    id: "lookbook-grid",
    name: "Commercial Lookbook Grid",
    subtitle: "Lưới Trưng Bày Thương Mại",
    badge: "Catalog Lookbook",
    category: "interactive-deck",
    description: "Bố cục lưới 2 cột sang trọng cho phép khách hàng nhìn tổng quan tất cả mẫu hoa cùng lúc.",
    tag: "Tổng quan danh mục",
    features: ["Bố cục lưới thương mại 2 cột", "Bộ lọc giá nhanh", "Nút chốt mẫu tức thời"],
    recommendedFor: "Phù hợp cho bộ sưu tập nhiều mẫu (>10 mẫu)",
  },
  "editorial-story": {
    id: "editorial-story",
    name: "Editorial Magazine & Story",
    subtitle: "Tạp Chí Nghệ Thuật & Cảm Xúc",
    badge: "Editorial Story",
    category: "interactive-deck",
    description: "Bố cục tạp chí nghệ thuật cao cấp với cuộn dọc Parallax và khung hình to bản nghệ thuật.",
    tag: "Cảm xúc & Chiều sâu",
    features: ["Khung ảnh to bản tỷ lệ 4:5 sang trọng", "Nút chốt mẫu cố định chân trang"],
    recommendedFor: "Hoa cưới, hoa kỷ niệm, bộ sưu tập giới hạn",
  },
  "video-reels": {
    id: "video-reels",
    name: "Video-First Reels & 360",
    subtitle: "Lướt Video Dọc Toàn Màn Hình",
    badge: "Video Reels",
    category: "interactive-deck",
    description: "Trải nghiệm lướt video dọc toàn màn hình 9:16 phong cách TikTok/Reels.",
    tag: "Trực quan sinh động",
    features: ["Khung nhìn 9:16 toàn màn hình", "Nút chốt mẫu 1-chạm nổi bật trên nền video"],
    recommendedFor: "Bó hoa khổng lồ, giỏ hoa đại tiệc, khách trẻ tuổi",
  },
  "occasion-budget-quiz": {
    id: "occasion-budget-quiz",
    name: "Occasion & Budget Matcher",
    subtitle: "Trợ Lý Gợi Ý Theo Dịp & Ngân Sách",
    badge: "Smart Matcher",
    category: "interactive-deck",
    description: "Trợ lý tương tác thông minh hỏi nhanh 2 câu: Dịp tặng và Ngân sách để chốt đơn trong 30 giây.",
    tag: "Chốt nhanh 30 giây",
    features: ["Bộ lọc dịp tặng thông minh", "Thang đo ngân sách", "Đề xuất nhanh"],
    recommendedFor: "Khách mua gấp, đơn giao hỏa tốc 60 phút",
  },
  "event-moodboard": {
    id: "event-moodboard",
    name: "Color Moodboard Gallery",
    subtitle: "Bảng Phối Màu & Concept Sự Kiện",
    badge: "Moodboard",
    category: "interactive-deck",
    description: "Phân loại và trưng bày theo dải phổ màu giúp khách hàng chọn hoa hợp phong thủy.",
    tag: "Đồng điệu sắc màu",
    features: ["Bảng chọn dải tông màu (Color Swatches)", "Nút chốt mẫu theo tông màu"],
    recommendedFor: "Hoa sự kiện, tiệc cưới, khai trương hợp mệnh phong thủy",
  },
  "split-compare": {
    id: "split-compare",
    name: "Split-Screen Lens & Focus",
    subtitle: "Soi Chi Tiết Chia Đôi Màn Hình",
    badge: "Detail Lens",
    category: "interactive-deck",
    description: "Thiết kế chia đôi màn hình: nửa trên soi cận cảnh cánh hoa, nửa dưới hiển thị thông số BOM.",
    tag: "Chính xác & Tinh xảo",
    features: ["Khung soi chi tiết hoa độ nét cao", "Thước đo đối sánh kích thước"],
    recommendedFor: "Hoa nhập khẩu đắt tiền, lan hồ điệp, khách hàng kỹ tính",
  },
}
