/**
 * Dữ liệu hành chính chuẩn hóa: Tỉnh/Thành phố và các Phường/Xã / Quận tiêu biểu của Việt Nam.
 * Phục vụ Cascading Address Selection + Autocomplete (Spec #8).
 * Pure TypeScript.
 */

export interface ProvinceData {
  name: string
  code: string
  wards: string[]
}

export const VN_POPULAR_PROVINCES: ProvinceData[] = [
  {
    name: "TP. Hồ Chí Minh",
    code: "HCM",
    wards: [
      "Phường Bến Nghé (Quận 1)",
      "Phường Bến Thành (Quận 1)",
      "Phường Tân Định (Quận 1)",
      "Phường Đa Kao (Quận 1)",
      "Phường Cầu Kho (Quận 1)",
      "Phường Cô Giang (Quận 1)",
      "Phường Thảo Điền (TP. Thủ Đức)",
      "Phường An Phú (TP. Thủ Đức)",
      "Phường Hiệp Bình Chánh (TP. Thủ Đức)",
      "Phường Tân Phong (Quận 7)",
      "Phường Tân Phú (Quận 7)",
      "Phường 1 (Quận 3)",
      "Phường 2 (Quận 3)",
      "Phường Võ Thị Sáu (Quận 3)",
      "Phường 1 (Quận 4)",
      "Phường 2 (Quận 5)",
      "Phường 1 (Bình Thạnh)",
      "Phường 2 (Phú Nhuận)",
      "Phường 1 (Tân Bình)",
      "Phường 1 (Gò Vấp)",
      "Phường Linh Trung (TP. Thủ Đức)",
      "Phường Hiệp Phú (TP. Thủ Đức)",
    ],
  },
  {
    name: "Hà Nội",
    code: "HN",
    wards: [
      "Phường Tràng Tiền (Hoàn Kiếm)",
      "Phường Hàng Bạc (Hoàn Kiếm)",
      "Phường Hàng Đào (Hoàn Kiếm)",
      "Phường Điện Biên (Ba Đình)",
      "Phường Kim Mã (Ba Đình)",
      "Phường Liễu Giai (Ba Đình)",
      "Phường Dịch Vọng (Cầu Giấy)",
      "Phường Yên Hòa (Cầu Giấy)",
      "Phường Trung Hòa (Cầu Giấy)",
      "Phường Bách Khoa (Hai Bà Trưng)",
      "Phường Ô Chợ Dừa (Đống Đa)",
      "Phường Láng Hạ (Đống Đa)",
      "Phường Mễ Trì (Nam Từ Liêm)",
      "Phường Mỹ Đình 1 (Nam Từ Liêm)",
      "Phường Quảng An (Tây Hồ)",
      "Phường Nhật Tân (Tây Hồ)",
    ],
  },
  {
    name: "Đà Nẵng",
    code: "DN",
    wards: [
      "Phường Hải Châu 1 (Hải Châu)",
      "Phường Thạch Thang (Hải Châu)",
      "Phường An Hải Bắc (Sơn Trà)",
      "Phường Phước Mỹ (Sơn Trà)",
      "Phường Khuê Mỹ (Ngũ Hành Sơn)",
      "Phường Hòa Cường Bắc (Hải Châu)",
      "Phường Hòa Khánh Bắc (Liên Chiểu)",
    ],
  },
  {
    name: "Cần Thơ",
    code: "CT",
    wards: [
      "Phường Tân An (Ninh Kiều)",
      "Phường An Cư (Ninh Kiều)",
      "Phường Xuân Khánh (Ninh Kiều)",
      "Phường An Khánh (Ninh Kiều)",
      "Phường Cái Khế (Ninh Kiều)",
    ],
  },
  {
    name: "Hải Phòng",
    code: "HP",
    wards: [
      "Phường Hoàng Văn Thụ (Hồng Bàng)",
      "Phường Minh Khai (Hồng Bàng)",
      "Phường Cầu Đất (Ngô Quyền)",
      "Phường Lạch Tray (Ngô Quyền)",
      "Phường Đằng Giang (Ngô Quyền)",
    ],
  },
  {
    name: "Bình Dương",
    code: "BD",
    wards: [
      "Phường Phú Cường (Thủ Dầu Một)",
      "Phường Hiệp Thành (Thủ Dầu Một)",
      "Phường Chánh Nghĩa (Thủ Dầu Một)",
      "Phường Lái Thiêu (Thuận An)",
      "Phường Dĩ An (Dĩ An)",
    ],
  },
  {
    name: "Đồng Nai",
    code: "DN_AI",
    wards: [
      "Phường Quyết Thắng (Biên Hòa)",
      "Phường Trung Dũng (Biên Hòa)",
      "Phường Thống Nhất (Biên Hòa)",
      "Phường Tân Phong (Biên Hòa)",
    ],
  },
  {
    name: "Khánh Hòa",
    code: "KH",
    wards: [
      "Phường Lộc Thọ (Nha Trang)",
      "Phường Phước Tiến (Nha Trang)",
      "Phường Vĩnh Nguyên (Nha Trang)",
    ],
  },
  {
    name: "Lâm Đồng",
    code: "LD",
    wards: [
      "Phường 1 (Đà Lạt)",
      "Phường 2 (Đà Lạt)",
      "Phường 3 (Đà Lạt)",
      "Phường 4 (Đà Lạt)",
    ],
  },
]

export const ALL_VN_PROVINCES: string[] = [
  "TP. Hồ Chí Minh",
  "Hà Nội",
  "Đà Nẵng",
  "Cần Thơ",
  "Hải Phòng",
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Tĩnh",
  "Hải Dương",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
]
